services:
  hapi:
    image: hapiproject/hapi:${FHIR_IMAGE_TAG:-v6.2.2}
    environment:
      SPRING_CONFIG_LOCATION: file:///opt/application.yaml
      hapi.fhir.server_address: https://hapi.${BASE_DOMAIN}/fhir/
      hapi.fhir.tester.home.server_address: https://hapi.${BASE_DOMAIN}/fhir
      spring.datasource.url: jdbc:postgresql://db:5432/hapifhir
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.datasource.driverClassName: org.postgresql.Driver
      spring.jpa.properties.hibernate.dialect: ca.uhn.fhir.jpa.model.dialect.HapiFhirPostgres94Dialect
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - ./application.yaml:/opt/application.yaml:ro

  db:
    image: postgres:${DB_IMAGE_TAG:-15}
    environment:
      POSTGRES_DB: hapifhir
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data:/data
    networks:
      - internal
volumes:
  db-data: {}
networks:
  # internal network for backing services
  internal:
