version: '3'

services:

  firely:
    depends_on:
      - db
    environment:
      # https://docs.fire.ly/projects/Firely-Server/en/latest/setting_up_firely_server/deployment/docker.html#running-docker-with-a-sql-server-container
      VONK_Repository: SQL
      VONK_SqlDbOptions:AutoUpdateConnectionString: Initial Catalog=VonkData;Data
        Source=db,1433;User ID=sa;Password=SQLServerStrong(!)Password*
      VONK_SqlDbOptions:AutoUpdateDatabase: "true"
      VONK_SqlDbOptions:ConnectionString: Initial Catalog=VonkData;Data Source=db,1433;User
        ID=sa;Password=SQLServerStrong(!)Password*
      VONK_SqlDbOptions:SchemaName: vonk

  db:
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: SQLServerStrong(!)Password*
    # healthcheck:
    #   test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P 'SQLServerStrong(!)Password*' -Q 'SELECT 1 FROM VonkData.sys.tables'
    #   interval: 1m30s
    #   timeout: 10s
    #   retries: 3
