version: '3'

services:

  firely:
    depends_on:
      db:
        condition: service_healthy
    environment:
      # https://docs.fire.ly/projects/Firely-Server/en/latest/setting_up_firely_server/deployment/docker.html#running-docker-with-a-sql-server-container
      VONK_Repository: SQL
      VONK_SqlDbOptions:AutoUpdateConnectionString: Initial Catalog=VonkData;Data
        Source=db,1433;User ID=sa;Password=SQLServerStrong(!)Password*
      VONK_SqlDbOptions:AutoUpdateDatabase: "true"
      VONK_SqlDbOptions:ConnectionString: Initial Catalog=VonkData;Data Source=db,1433;User
        ID=sa;Password=SQLServerStrong(!)Password*
      VONK_SqlDbOptions:SchemaName: vonk
    networks:
      - internal
      - ingress

  db:
    image: mcr.microsoft.com/mssql/server:${DB_IMAGE_TAG:-2022-latest}
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: SQLServerStrong(!)Password*
    healthcheck:
      test:
        - CMD
        # https://learn.microsoft.com/en-us/sql/tools/sqlcmd/sqlcmd-utility
        - /opt/mssql-tools/bin/sqlcmd

        # terminate batch job if there is an error
        - -b

        # Specifies the instance of SQL Server to which to connect
        - -S localhost

        # The login name or contained database user name
        - -U
        - sa

        # A user-specified password
        - -P
        - SQLServerStrong(!)Password*

        # Executes a query when sqlcmd starts and then immediately exit
        - -Q
        - SELECT 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - internal

networks:
  # internal network for backing services
  internal:
