version: '3'

services:

  firely:
    depends_on:
      - db
    environment:
      # https://docs.fire.ly/projects/Firely-Server/en/latest/setting_up_firely_server/deployment/docker.html#running-docker-with-a-sql-server-container
      VONK_Repository: SQL
      VONK_SqlDbOptions:AutoUpdateConnectionString: Initial Catalog=VonkData;Data
        Source=db,1433;User ID=sa;Password=SQLServerStrong(!)Password*
      VONK_SqlDbOptions:AutoUpdateDatabase: "true"
      VONK_SqlDbOptions:ConnectionString: Initial Catalog=VonkData;Data Source=db,1433;User
        ID=sa;Password=SQLServerStrong(!)Password*
      VONK_SqlDbOptions:SchemaName: vonk
      # Admin DB configuration
      # https://docs.fire.ly/projects/Firely-Server/en/latest/maintenance/administration_api.html
      VONK_Administration:Repository: SQL
      VONK_Administration:SqlDbOptions:SchemaName: vonkadmin
      VONK_Administration:SqlDbOptions:ConnectionString: Initial Catalog=VonkAdmin;Data Source=db,1433;User ID=sa;Password=SQLServerStrong(!)Password*
      VONK_Administration:SqlDbOptions:AutoUpdateDatabase: "true"
      VONK_Administration:SqlDbOptions:AutoUpdateConnectionString: Initial Catalog=VonkAdmin;Data Source=db,1433;User ID=sa;Password=SQLServerStrong(!)Password*
    networks:
      - internal
      - ingress

  db:
    image: mcr.microsoft.com/mssql/server:${DB_IMAGE_TAG:-2022-latest}
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: SQLServerStrong(!)Password*
    networks:
      - internal

networks:
  # internal network for backing services
  internal:
