version: "3.4"
services:
  portainer:
    image: portainer/portainer-ce:2.18.3
    command:
      - --admin-password=${ADMIN_PASSWD:?}
      - --host=unix:///var/run/docker.sock
      - --no-analytics
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer-${COMPOSE_PROJECT_NAME}.rule=Host(`portainer.${BASE_DOMAIN}`)
      - traefik.http.routers.portainer-${COMPOSE_PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.portainer-${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.portainer-${COMPOSE_PROJECT_NAME}.tls.certresolver=letsencrypt

      # portainer EXPOSEs multiple ports; use HTTP port
      - traefik.http.services.portainer-${COMPOSE_PROJECT_NAME}.loadbalancer.server.port=9000
    networks:
      - ingress

networks:
  # ingress network
  ingress:
    external: true
    name: external_web

volumes:
  portainer_data: {}
